# Generated by Django 5.2.10 on 2026-01-24 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pd_consent_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="PersonalDataConsent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(db_index=True, max_length=32, unique=True)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Согласие на обработку ПД",
                "verbose_name_plural": "Согласия на обработку ПД",
            },
        ),
    ]

