# Generated by Django 5.2.10 on 2026-01-25 08:24

import django.db.models.deletion
import django.db.models.functions.text
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0004_alter_master_image_alter_master_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код')),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='Скидка, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='appointments_promocode_discount_percent_range'), models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='appointments_promocode_code_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='MasterShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Пн ... 6=Вс', verbose_name='День недели')),
                ('starts_time', models.TimeField(verbose_name='Начало')),
                ('ends_time', models.TimeField(verbose_name='Окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='salons.master', verbose_name='Мастер')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_shifts', to='salons.salon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Смена мастера',
                'verbose_name_plural': 'Смены мастеров',
                'indexes': [models.Index(fields=['salon', 'weekday'], name='app_shift_sal_wd_idx'), models.Index(fields=['master', 'weekday'], name='app_shift_mst_wd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='shift_weekday')],
            },
        ),
        migrations.CreateModel(
            name='BookingHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('base_price', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_holds', to='salons.master')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_holds', to='salons.salon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_holds', to='salons.service')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.promocode')),
            ],
            options={
                'indexes': [models.Index(fields=['master', 'starts_at'], name='hold_master_starts_idx'), models.Index(fields=['expires_at'], name='hold_expires_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон клиента')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Имя клиента')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('base_price', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('booked', 'Записан'), ('cancelled', 'Отменён')], default='booked', max_length=16)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='salons.master')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.salon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.promocode')),
            ],
            options={
                'indexes': [models.Index(fields=['master', 'starts_at'], name='appt_master_starts_idx'), models.Index(fields=['salon', 'starts_at'], name='appt_salon_starts_idx')],
            },
        ),
    ]
