# Generated by Django 5.2.10 on 2026-01-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='salons/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/'),
        ),
    ]
