# Generated by Django 5.2.10 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0002_salon_image_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="masters/"),
        ),
    ]

